### ISSUE TITLE
.destroy() throws error (2.1.4)

### ISSUE THREAD

**Issue by michal-novacek** [moxiecode/plupload#1252]
Hello, I am using the plupload in dialog and calling destroy on dialog close. This is the error I get:

    "TypeError: Cannot read property 'appendChild' of null at n.e.extend.getShimContainer (http://builder.dev.    com:5262/assets/65126102906651790/vendor/plupload/plupload.full.min.js:13:23600)
    at n.t.extend.destroy (http://builder.dev.com:5262/assets/65126102906651790/vendor/plupload/plupload.full.min.js:14:21767)
    at n.l.exec (http://builder.dev.com:5262/assets/65126102906651790/vendor/plupload/plupload.full.min.js:13:22657)
    at n.e.extend.shimExec (http://builder.dev.com:5262/assets/65126102906651790/vendor/plupload/plupload.full.min.js:13:23736)
    at n.e.extend.exec (http://builder.dev.com:5262/assets/65126102906651790/vendor/plupload/plupload.full.min.js:13:23869)
    at n.e.extend.destroy (http://builder.dev.com:5262/assets/65126102906651790/vendor/plupload/plupload.full.min.js:13:29221)
    at http://builder.dev.com:5262/assets/65126102906651790/vendor/plupload/plupload.full.min.js:28:11496
    at Object.n [as each] (http://builder.dev.com:5262/assets/65126102906651790/vendor/plupload/plupload.full.min.js:13:3320)
    at n.D (http://builder.dev.com:5262/assets/65126102906651790/vendor/plupload/plupload.full.min.js:28:11475)
    at n.<anonymous> (http://builder.dev.com:5262/assets/65126102906651790/vendor/plupload/plupload.full.min.js:28:14560)"

Any idea what could be causing this?

**Comment by michal-novacek** [comment]
Calling .unbindAll() before the .destroy() helped. I would expect that to be done internally by .destroy()

**Comment by jayarjo** [comment]
It is done internally. Should be something else. We do not encounter this in our unit tests. Would be interesting to look at your case.
